services:
  - type: web
    name: indcad-api
    env: python
    plan: free
    branch: main
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -w 4 -b 0.0.0.0:$PORT app:app"
    envVars:
      - key: ADMIN_USER
        sync: false
      - key: ADMIN_PASS
        sync: false
      - key: PUBLIC_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: OPENAI_MODEL
        value: text-embedding-3-small
        sync: false
      - key: CORS_ORIGINS
        value: "*"
        sync: false
